uktrade/find-business-regulations

orp/config/urls.py, orp/orp_search/config.py, orp/orp_search/dummy_data.py, orp/orp_search/public_gateway.py, orp/orp_search/templates/details.html, orp/orp_search/templates/orp.html, orp/orp_search/views.py
Removed construction-data.csv from the orp_search directory. The file contained deprecated safety and regulation guidance for various construction topics, which are now available in updated formats elsewhere in the project.
=> orpd-38: feat:delete outdated construction-data.csv and added endpoint support for details

orp/orp_search/views.py
If 'query' is not in the request GET parameters, the view now redirects to the homepage with an empty query string. This ensures users don't face errors when accessing the search page without a query parameter.
=> fix:add redirect for missing query in search view

orp/orp_search/views.py
Eliminated redirect when "query" parameter is missing from GET request in the search view. This change simplifies the code and avoids unnecessary redirection logic, improving overall maintainability.
=> temp:remove unused redirect in orp_search views

orp/config/urls.py, orp/orp_search/templates/orp.html, orp/orp_search/views.py
Introduced a new view `download_search_csv` to generate search results as a CSV file. Updated the template to dynamically set the CSV download link with current query parameters. Adjusted the URL configuration to include the route for CSV download.
=> feat:Add CSV download feature for search results

orp/orp_search/public_gateway.py, orp/orp_search/views.py
Refactor pagination to use Django Paginator for improved reliability. The context is now updated with pagination details and results are consistently aggregated across all pages for accurate representation.
=> chore:enhance pagination handling for search results

orp/orp_search/public_gateway.py
Updated variable names from 'paginated_reports' to 'paginated_documents' for consistency and clarity in the pagination context. This change ensures that the nomenclature better reflects the content being paginated.
=> refactor:rename paginated variables from reports to documents

orp/orp_search/public_gateway.py, orp/orp_search/templates/orp.html
- adds no results found content
- adds page no. to title
- shows docs shown in results header (1 to 10, 11 to 20 etc.)
- hides sorting when no results
=> feature/ORPD-58 - No results found

orp/orp_search/views.py
Disable the code block responsible for searching and processing legislation within the ORP search views. This helps to reduce unnecessary execution of code when no search terms or specific document types are provided.
=> temp:comment out unused legislation search logic in views.py

orp/config/urls.py, orp/orp_search/templates/orp.html, orp/orp_search/templates/react-orp.html, orp/orp_search/views.py, orp/templates/base.html
- Puts React search as the root app (`/`)
- Redirects to non JavaScript version of search when browser detects JS is off (`/nojs`)
- Adds link to switch between version for development purposes
=> feature/ORPD-86 - Redirect to non-js search when user has JS off.

orp/config/urls.py, orp/orp_search/models.py
Modified the URL path for the RebuildCacheViewSet and adjusted the base URL to include "api/". Updated the DataResponseModel to change the identifier field from URLField to TextField to allow greater flexibility.
=> update:URL paths and change DataResponseModel.identifier field

orp/config/urls.py, orp/orp_search/utils/paginate.py, orp/orp_search/utils/search.py
Introduced a new `PublishersViewSet` with a `publishers` endpoint to retrieve distinct publisher names from the database. Updated URL routing to accommodate the new endpoint and added necessary imports and utility functions.
=> feat:add new Publishers API endpoint and updated response values

orp/orp_search/config.py
Previously, document_types and publisher_names were processed even if they were None, which caused errors. Now, these attributes are explicitly checked for None and handled appropriately to ensure stability and robustness in data processing.
=> fix:handle None values in document_types and publisher_names

orp/orp_search/apps.py, orp/orp_search/config.py, orp/orp_search/construction_legislation.py, orp/orp_search/legislation.py, orp/orp_search/models.py, orp/orp_search/utils/documents.py, orp/orp_search/utils/paginate.py, orp/orp_search/utils/search.py, orp/orp_search/views.py
chore:add detailed docstrings to various modules and functions
This commit introduces comprehensive docstrings across multiple files in the project to improve code readability and maintainability. These additions clarify the purpose, parameters, returns, and additional notes for existing functions, methods, and class definitions. Enhanced documentation will aid future developers in understanding the codebase more efficiently.
update:logging levels from info to debug
Changed all logger.info statements to logger.debug for less verbose logging in non-critical areas. This reduces log clutter and focuses info-level logging on more significant events.
=> feat(orpd-23):cleanup

orp/orp_search/tests/test_search.py
This commit introduces a new test case to validate the combination of OR and AND operations within a single search query. The test checks the correct instantiation of SearchQuery objects and verifies the application of OR and AND logical operations.
=> chore:add test for single OR and AND operations in search query

Makefile, README.md
This commit adds a new 'setup_local' command to the Makefile for setting up the service, database, and cache locally, providing a convenient way to initialize the development environment. Additionally, it renames 'rebuild_cache_man' to 'rebuild_cache' for clarity and updates the README to reflect these changes. These adjustments aim to enhance developer efficiency and streamline the onboarding process.
=> chore:introduce local setup command and update cache target

fbr/cache/tasks.py, fbr/config/celery.py, fbr/config/settings/base.py
Integrate Celery into the project by configuring broker and result backend with Redis, adding necessary settings, and setting up periodic task scheduling with Django Celery Beat. The rebuild_cache task is now a bound task, allowing it to access task-specific features. Additionally, configuration changes in the Celery app include environment setup and periodic task scheduling.
=> chore:add Celery and Django Celery Beat configuration

fbr/cache/legislation.py, fbr/cache/public_gateway.py
Updated the initial value of `inserted_document_count` to 1 to more accurately reflect insertion logic. Introduced `valid_sort_date` in `legislation.py` to default to `modified` date if `valid` date is missing or empty, ensuring correct sorting behavior.
=> fix: document count logic and ensure valid sort dates.

fbr/config/celery.py
<details>
<summary>Details</summary>
- Updated path from "config.settings.local" to "fbr.config.settings.local"
- Ensures Celery uses correct settings, reducing misconfiguration errors
</details>
=> fix: Correct Django settings module path in Celery config

fbr/config/celery.py
This pull request updates the Celery configuration to use the local settings module, ensuring consistency and simplifying the setup process.
=> Set Django settings for Celery configuration

fbr/config/celery.py, fbr/config/settings/base.py
Added UTC settings for Celery to ensure task scheduling consistency across environments. Corrected the DJANGO_SETTINGS_MODULE path for Celery configuration, aligning it with the project's structure. These changes help improve maintainability and prevent timezone-related issues.
=> chore:set Celery to UTC and fix settings module path.

fbr/cache/tasks.py, fbr/config/celery.py, fbr/config/settings/local.py
refactor:module paths and refine Celery configuration.
Correct the import path for settings in Celery to ensure it uses the proper local configuration. Simplify the cache references by updating module names, ensuring clarity, and removing unnecessary task bindings for rebuild_cache. These changes improve code maintainability and readability while aligning with project structure standards.
=> refactor:module paths and refine Celery configuration.

fbr/cache/tasks.py, fbr/config/celery.py, fbr/config/settings/local.py
This commit refactors the Celery task setup by moving `tasks.py` to a new location under `fbr/cache`. It replaces the deprecated `shared_task` with direct Celery app task registration and adjusts the configuration to use a periodic task setup function. Additionally, unnecessary code has been removed from the local settings file.
=> refactor: cache task setup for Celery integration

fbr/config/settings/local.py
This update sets USE_DEPRECATED_PYTZ to False in the local settings file, indicating that the application should not use the deprecated pytz library. This change ensures compatibility with future updates and promotes using more modern timezone handling libraries.
=> Disable deprecated pytz usage in local settings 

fbr/config/celery.py, fbr/config/settings/local.py
This pull request removes the deprecated pytz usage from the local settings file and refactors the Celery configuration for better performance and compatibility.
=> Remove deprecated pytz usage and refactor Celery configuration

fbr/config/celery.py, fbr/manage.py
- Ensure Django setup is configured early in manage.py to avoid configuration issues during application start-up.
- Streamline initialization by relocating Django setup to the beginning of the file.
- Remove redundant Django setup in celery.py for improved efficiency.
=> Initialize Django setup at the start of manage.py

fbr/config/celery.py, fbr/manage.py
The pull request enhances the Django setup in manage.py and updates Celery configuration for consistency and adaptability in various environments.
=> Refactor environment setup for improved execution

fbr/config/celery.py
This pull request corrects the path for the DJANGO_SETTINGS_MODULE environment variable in the Celery configuration file. It ensures the application loads the correct settings module, preventing potential misconfigurations during runtime.
=> Fix Django settings module path in Celery configuration

app/cache/legislation.py, app/cache/manage_cache.py, celery_worker/settings.py, celery_worker/tasks.py, docker-compose.yml, fbr/celery_app.py
Replaced Celery worker settings with `celery_worker.settings` for better separation and refactored setup logic in `tasks.py`. Adjusted timeouts, removed unused imports, and improved cache management logic. Updated `docker-compose` health check settings to reduce start period.
=> refactor: Celery worker and update related configurations.

fbr/settings.py
Replaced the local memory cache configuration with a commented Redis cache setup for future use. This prepares the settings file for an eventual transition to Redis as the caching backend.
=> fix:commented out use Redis-based caching (commented for future implementation)

paas_entrypoint.sh
Simplified the deployment process by removing the use of poetry for running commands. This eliminates unnecessary dependencies and ensures compatibility with environments lacking poetry installed.
=> chore:remove poetry commands from deployment script

fbr/settings.py, paas_entrypoint.sh
Revised the Gunicorn startup command to reference `fbr.wsgi:application` instead of `config.wsgi`. This ensures the correct WSGI application module is used when the server starts.
=> update:Gunicorn command to use correct WSGI application path

paas_entrypoint.sh
Replaced Poetry commands with direct Python execution for migrations and server startup. Simplifies the script and removes dependency on Poetry for runtime execution.
=> remove:Poetry usage from deployment script.

fbr/settings.py
Replaced the existing database connection logic with the `database_url_from_env` utility from `dbt_copilot_python` for cleaner and more standardized configuration. Removed the previous fallback logic for SQLite, assuming consistent reliance on environment variables.
=> refactor:database configuration to use dbt_copilot utility

fbr/settings.py
Revised database configuration to retrieve credentials dynamically via `DATABASE_CREDENTIALS` from environment variables. Removed fallback to SQLite and deprecated `DATABASE_URL` usage. Added a debug statement to log database credentials for validation during setup.
=> refactor:database settings for dynamic credential handling

fbr/settings.py
Replaced hardcoded database configuration with a dynamic setup using `database_url_from_env`. This ensures better flexibility by supporting environment-based database credentials and providing a fallback to static defaults. Removed unnecessary debug prints for cleaner code.
=> refactor:database configuration logic in settings.py

fbr/settings.py
Added the "engine" parameter explicitly as "postgresql" when configuring the database URL. This ensures consistency and clarity in database connection handling. Simplified the default database URL parsing for cleaner fallbacks.
=> update:database configuration to explicitly set engine

app/search/config.py, app/search/views.py
- Improved search logic for clarity and maintainability.
- Strengthened query handling and prevented SQL injection risks.
- Enhanced security and functionality with updated dependencies.
=> refactor: enhance search functionality and security

fbr/settings.py
Added conditional initialization of Sentry to ensure it is only configured when a SENTRY_DSN environment variable is set. Updated the logging configuration to include a Sentry-specific logger for error-level messages. This improves flexibility and avoids unnecessary overhead when Sentry is not used.
=> chore:initialize Sentry only when SENTRY_DSN is provided.

fbr/settings.py
<summary>Details</summary>
This pull request enhances the Sentry SDK initialization process by optimizing the setup and improving logging configurations. Key changes include:
- Checking `SENTRY_DSN` once at the beginning for a cleaner approach.
- Adding an info-level log message when Sentry is disabled.
- Explicitly adding Sentry to loggers for better observability.
</details>
=> chore: Improve Sentry SDK initialization and logging

fbr/settings.py
- Add logging messages to provide clarity on the Sentry configuration state.
- Log when Sentry is enabled or disabled, and skip related logging configuration if Sentry is not active.
=> minor:enable logging messages for Sentry initialization status

fbr/settings.py
- Updated the `CELERY_TASK_TIME_LIMIT` from 15 minutes to 30 minutes for longer-running tasks.
=> chore:increase Celery task time limit to 30 minutes

app/core/views.py, fbr/urls.py
The `test_sentry` endpoint and its associated URL have been removed from core views and URLs as they are no longer needed. This cleanup helps eliminate unused code, improving maintainability and reducing potential clutter in the project.
=> remove:test_sentry endpoint from core views and URLs

celery_worker/tasks.py, fbr/settings.py
Reordered cache-building tasks in `tasks.py` for correct execution sequence. Extended Celery task time limit to 60 minutes in `settings.py` to support longer processes.
=> fix: reorder cache-building tasks and extend Celery task time limit

fbr/urls.py
Updated logic to separate publishers into "standard/guidance" and "legislation" categories. Grouped legislation items under a single object to streamline the response structure. This improves clarity and better aligns with data organization requirements.
Navigate to: `GET /api/v1/retrieve/document-types/` and you should see something similar to:
```
{
"non-legislation": [
{
"label": "Guidance",
"name": "Guidance"
},
{
"label": "Standard",
"name": "Standard"
},
{
"label": "Statutory Guidance",
"name": "Statutory guidance"
}
],
"legislation": [
{
"label": "European Union Decision",
"name": "EuropeanUnionDecision"
},
{
"label": "European Union Directive",
"name": "EuropeanUnionDirective"
},
{
"label": "European Union Regulations",
"name": "EuropeanUnionRegulations"
},
{
"label": "Northern …
```
=> refactor(urls): reorganize document type results by category
