Makefile
local.env.example
orp/config/settings/base.py
orp/core/admin.py

The admin and auth packages allow us to check if the database is connected and working when running django locally

Adds back in django admin and auth functionality

---

orp/orp_search/config.py
orp/orp_search/construction-data.csv
orp/orp_search/models.py
orp/orp_search/public_gateway.py
orp/orp_search/views.py

Implemented pagination and sorting functionality in the search results. Updated filter conditions, added pagination logic, introduced new config parameters, and adjusted the dataset to support these features.

feat:add pagination and sorting to search results

---

orp/orp_search/dummy_data.py
orp/orp_search/public_gateway.py
orp/orp_search/templates/orp.html
orp/orp_search/views.py

Changed the filter criteria in `public_gateway.py` to use `publisher_id` instead of `publisher`. Updated HTML templates to match new publisher_id values and adjusted views.py to handle `publisher` via query parameters. Enhanced dummy data to include `publisher_id` for consistency.

feat:improve publisher search by using publisher_id and support query params

---

orp/orp_search/config.py
orp/orp_search/public_gateway.py
orp/orp_search/templates/orp.html
orp/orp_search/views.py

Enhanced search functionality by adding a new sorting option based on relevance. The relevance score is calculated using the presence of search terms in the document title and description. Updated the configuration validation, HTML template, and logging to support this new sorting method.

orpd-52 - feat:add sorting by relevance

---

orp/orp_search/public_gateway.py
orp/orp_search/views.py

Refactored the pagination logic in `public_gateway.py` to improve clarity and manage pagination exceptions better.

refactor:pagination logic

---

orp/orp_search/public_gateway.py

Consolidate the context dictionary by removing redundant variables and clarifying names. This change simplifies the code and ensures that relevant pagination information is correctly passed to the template.

refactor:context variables for search pagination

---

orp/core/forms.py
orp/core/templatetags/url_replace_tags.py
orp/orp_search/templates/document.html
orp/orp_search/templates/orp.html
orp/orp_search/views.py

- Adds url_replace simple_tag to update page in query
- Adds pagination frontend ✨ 
- changes 'query' to 'search' in url
- fixes nan issue on document page 👵
- adds "clear all filters" functionality

ORPD-47 - Pagination

---

orp/orp_search/legislation.py
orp/orp_search/public_gateway.py
orp/orp_search/views.py

Introduced a new Legislation class to handle legislation-specific searches and integrated it into the search view.

chore:add legislation search functionality and refactor logging

---

orp/orp_search/views.py

Updated the `download_search_csv` function to handle multiple document types for both public gateway and legislation searches. This includes collecting results from different sources and combining them before generating the CSV.

chore:enhance search CSV download to include multiple doc types.

---

orp/orp_search/legislation.py
orp/orp_search/views.py

Updated the API result count from 100 to 20 for better performance. Fixed pagination handling by correctly iterating through remaining pages and avoiding nested structure issues. Removed redundant checks for empty search terms in views.py to streamline the search process.

chore:reduce result count and fix pagination handling

---

orp/orp_search/views.py

Introduced a utility function to parse dates ensuring proper handling of datetime objects and strings. Improved search result sorting by modifying sorting logic to consider date_modified, ensuring consistent ordering of results.

feat: add date parsing utility and improve sorting

---

orp/orp_search/config.py
orp/orp_search/legislation.py
orp/orp_search/utils/paginate.py
orp/orp_search/utils/results.py
orp/orp_search/utils/terms.py
orp/orp_search/views.py

Added a new utility function `combine_search_terms` to merge `AND` and `OR` search terms into a single expression. Updated `SearchDocumentConfig` to use this combined expression and modified `search` method in `legislation.py` to use the new combined search terms. This improves query precision and flexibility.

chore:enhance search functionality with combined search terms

---

orp/orp_search/utils/search.py

Integrated partial matching using TrigramSimilarity and combining search queries for granular full-text search. This improves the search results by accounting for partial word matches and provides a more flexible search experience.

chore:enhance search functionality with partial matches

---

orp/config/urls.py
orp/orp_search/utils/search.py
react_front_end/src/App.js
react_front_end/src/components/AppliedFilters.js
react_front_end/src/components/Results.js
react_front_end/src/hooks/useQueryParams.js
react_front_end/src/utils/constants.js
react_front_end/src/utils/fetch-drf.js

- Adds in dynamic publishers component
- Allows filter by publishers
- useQueryParams now only uses Array type... again.

feature/ORPD-102 - publishers endpoint

---

orp/orp_search/tests/test_search.py
orp/orp_search/utils/documents.py
orp/orp_search/utils/search.py
pytest.ini

feat(orpd-54):search terms unit test

---

Procfile
docker-compose.yml
fbr/config/celery.py
fbr/config/settings/base.py

Integrated Redis and Celery by updating docker-compose with new services and modifying the Procfile and settings. Celery workers and beat are included for async task management, with Redis as the broker. Adjusted Celery configurations to use the extended result format and ensure proper task processing.

chore: add Redis and Celery support to the project.

---

fbr/config/celery.py

- Updated Celery configuration to utilize an environment variable for Django settings.
- Enhances flexibility and simplifies configuration management across environments.
- Improves robustness in deployment scenarios.

update Celery configuration to use environment variable for settings

---

fbr/config/celery.py

- Updated Celery configuration to directly import the local settings module, simplifying the setup and reducing dependency on environment variables.
- Ensures consistency in Celery app behavior across different environments.

configure Celery app with local settings module

---

fbr/config/celery.py

This pull request includes changes to update the Celery configuration to use the environment variable for the Django settings module. This enhancement ensures easier configuration management and improves robustness in deployment scenarios.

Update Celery Configuration for Django Settings Module

---

fbr/cache/tasks.py
fbr/config/celery.py
fbr/config/settings/base.py
fbr/config/settings/local.py

- Included the "fbr.cache" app for enhanced cache management.
- Configured Celery with task time limits and improved task functions.
- Refined error messages and added retry logic for clarity.

Add cache app and improve Celery configuration

---

fbr/__init__.py
fbr/config/celery.py
fbr/tasks.py
poetry.lock
pyproject.toml

- Renamed tasks module for clarity
- Updated Celery task naming
- Upgraded Redis package version
- Improved app initialization during Django startup
- Fixed Django settings module path in Celery configuration
- Enhanced environment and Celery configuration setup
- Streamlined Django setup for improved execution
- Removed deprecated pytz usage and updated Celery setup
- Refactored Celery task setup for better integration

refactor: Update configuration for better Celery integration

---

fbr/search/templates/intro.html
react_front_end/src/App.js

Updates h1s to: `Find business regulations and guidance`
Change document type label to: `Document type`

ORPD-134 - change h1s to align with designs

---

fbr/cache/manage_cache.py
fbr/cache/tasks.py
fbr/config/celery.py
local_deployment/Dockerfile

- Moved and renamed cache task modules for better organization.
- Updated task references and configurations as needed.
- Streamlined Docker build by removing unnecessary dependencies.
- Enhanced Django environment setup for improved configuration.

refactor: Improve cache task structure and dependencies

---

fbr/config/settings/local.py

<Details of the pull request changes>
- Update cache app module path in local settings
- Refactor cache task structure and update dependencies
- Refactor task module and update redis dependency
- Fix Django settings module path in Celery config
- Refactor environment and Celery configuration setup
- Initialize Django setup earlier in manage.py
- Remove deprecated pytz usage and setup Django in Celery
- Enable support for deprecated pytz in Celery
- Disable deprecated pytz usage in local settings
- Refactor cache task setup for Celery integration

refactor: update cache and task modules

---

celery_worker/tasks.py
fbr/celery_app.py

Removed unnecessary Django setup from `rebuild_cache` task to streamline function execution. Added project root to `sys.path` in `celery_app.py` to ensure proper module resolution. Updated the cache task schedule to a new time.

refactor: Celery setup and update task scheduling.

---

paas_entrypoint.sh

Updated the script to use Poetry for running Django migrations and starting the Gunicorn server. This ensures consistency in the execution environment and aligns with the project's dependency management setup.

chore:Use Poetry to run migration and Gunicorn commands

---

fbr/settings.py

Introduced the `setup_allowed_hosts` function to dynamically adjust the `ALLOWED_HOSTS` based on the environment configuration. This improves flexibility and ensures proper handling of host settings across environments.

chore:Set up dynamic processing for ALLOWED_HOSTS.

---

.github/workflows/code_quality.yml
fbr/celery_app.py
fbr/settings.py

From FBR_DATABASE_APPLICATION_USER to DATABASE_CREDENTIALS

chore:changed database env name

---

app/core/management/commands/rebuildcache.py
fbr/settings.py

Introduce a new Django management command to rebuild the cache, improving cache management capabilities. Update database configuration logic to dynamically handle DATABASE_URL and provide fallback to SQLite for better environment flexibility.

Add cache rebuild command and update database config logic

---

app/search/templates/django-fbr.html
app/search/utils/paginate.py
app/search/utils/search.py
app/search/views.py

Updated search handling to include "search" as a backup query. Included regulation search form in the context and implemented explicit pagination for clearer document results. Adjusted frontend to align with new pagination approach.

chore:improve search handling and pagination behavior (django/nojs)

---

app/search/views.py
fbr/urls.py

<description>
- Introduce endpoints for downloading search results as CSV for both JS and no-JS versions
- Added helper function to dynamically determine base URL
- Updated CSV download logic to include document URLs in the output
</description>

fix(orpd-139):CSV download endpoints and enhance download view

---

app/cache/apps.py
app/search/config.py
app/search/utils/search.py
app/search/views.py

- Revised logging levels to utilize `logger.debug`
- Provides more granular logs without clutter
- Improves clarity and debugging capabilities
- Added debug statements for parameter sanitization

chore(orpd-140):switch logging from info to debug for detailed insights

---

app/search/views.py
fbr/urls.py

<details>
<summary>Details</summary>
</details>

remove: Remove TempCacheDataResponseViewSet and Improve JSON Parsing

---

app/cache/public_gateway.py
fbr/urls.py

<details>
<summary>Details</summary>
- Reduced request timeout for improved responsiveness
- Added detailed timing logs for various operations
- Enhanced error handling for fetching titles
- Replaced `ModelViewSet` with `ViewSet` for `DataResponseViewSet`
</details>

refactor:optimize request handling and add detailed timing logs

---

app/cache/public_gateway.py
app/core/forms.py
app/core/views.py
app/search/templates/django-fbr.html
app/search/templates/document.html
app/templates/base.html
app/templates/feedback.html
app/templates/feedback_confirmation.html
app/templates/form_errors/form_error_summary.html
app/templates/form_errors/single_input_error_messages.html
fbr/settings.py
front_end/stylesheets/filters.scss
front_end/stylesheets/helpers.scss
front_end/stylesheets/search.scss
react_front_end/src/App.js
react_front_end/src/components/AppliedFilters.js
react_front_end/src/components/CheckboxFilter.js
react_front_end/src/components/DevToggle.js
react_front_end/src/components/Results.js
react_front_end/src/components/SortSelect.js

Adds feedback form with validation and feedback confirmation/error page.

feature/ORPD-159 - feedback form

---

app/search/templates/django-fbr.html
app/templates/base.html
fbr/context_processors.py
fbr/settings.py

- Adds environment conditionals
- Hides "JavaScript on/off version" link on prod.

feature/ORPD-176 - environment conditionals

---

app/core/templates/accessibility_statement.html
app/core/templates/cookies.html
app/core/templates/disclaimer.html
app/core/templates/privacy_notice.html
app/core/views.py
app/search/templates/document.html
app/search/templates/intro.html
app/search/views.py
app/templates/base.html
app/templates/feedback_confirmation.html
fbr/settings.py
fbr/urls.py

- Adds disclaimer page and link in footer
- Fixes page titles
- Uses constant for service name and long service name throughout

feature/ORPD-178 - disclaimer page

---

app/cache/legislation.py
app/search/migrations/0001_initial.py
app/search/models.py
app/search/utils/calculate_score.py
app/search/utils/documents.py
app/search/utils/search.py
fbr/settings.py

This pull request refactors the search scoring logic and enhances query handling mechanisms to offer better flexibility and reliability.
- Migrated `calculate_score` function to a dedicated module for better code modularity.
- Replaced model-level static scoring fields with dynamic score annotations in database queries.
- Improved handling for both strict and partial search queries.
- Added error logging for better issue diagnosis.
- Adjusted default query operators to enhance query flexibility.

Improve search scoring logic and query handling

---

Makefile
app/cache/legislation.py
app/cache/manage_cache.py
app/cache/public_gateway.py
app/search/config.py
app/search/utils/documents.py
app/search/utils/retrieve_data.py
app/search/utils/search.py
app/search/views.py
celery_worker/tasks.py
fbr/celery_app.py
fbr/settings.py

This pull request introduces several improvements to caching and error-handling mechanisms throughout the codebase:
- Unified `get_data_from_url` utility for URL data fetching, replacing duplicate methods to improve code reuse and maintainability.
- Enhanced logging for better traceability in caching and error-handing processes.
- Added robust error handling to cache building processes.
- Refactored title fetching for related legislation into a reusable utility.
- Updated task configurations, including time limits and schedules, for improved performance and reliability.
- Improved responses, providing more detailed timing and error information during cache rebuild operations.

refactor:caching logic and enhance error handling

---

app/cache/legislation.py
app/cache/public_gateway.py
app/search/utils/documents.py
app/search/views.py

This pull request:
- Replaces `generate_short_uuid` with the improved `generate_uuid` function. The new function supports optional text input for generating deterministic IDs.
- Enhances API consistency by adding HTTP status codes and detailed error messages to the document retrieval view. 
_No related issues are linked to this pull request._

feat(orpd-199):update UUID generation and improve document error handling

---

app/search/utils/calculate_score.py
app/search/utils/search.py

Enhanced the searching functionality by adding `nulls_last` to sort queries. This ensures null values are consistently placed at the end, providing a more predictable and user-friendly order for search results.

feat(search): improve ordering logic with nulls last

---

app/core/templatetags/custom_date_tags.py
app/search/templates/document.html
app/search/utils/date.py
app/search/utils/paginate.py
react_front_end/src/components/Results.js
react_front_end/src/components/__tests__/Results.test.js
react_front_end/src/utils/fetch-drf.js

This pull request includes several changes to improve the handling and display of partial dates in the application. The changes involve updates to both the backend and frontend code to ensure that dates are formatted correctly and consistently.
Backend changes:
* [`app/core/templatetags/custom_date_tags.py`](diffhunk://#diff-137a121f17af5a3fd121b819545c6f0c0799038ebbd21cf35cd457603c3ad2f2R1-R10): Added a custom template filter `format_partial_date` to format partial dates using the `format_partial_date_govuk` function.
* [`app/search/utils/date.py`](diffhunk://#diff-5629a9aabdb69024dbec0cbfac81cde789d31b3981b13a76ba352e1c20e9c861R47-R68): Added the `format_partial_date_govuk` function to handle different date formats (year, year-month, year-month-day) and return them in a GOV.UK style.
* …

feature/ORPD-219 - show source dates

---

app/search/templates/django-fbr.html
front_end/stylesheets/helpers.scss
react_front_end/src/App.js
react_front_end/src/components/CheckboxFilter.js
react_front_end/src/components/ResultsCount.js

This pull request includes several changes to enhance the accessibility and functionality of the search and filter components in the front-end codebase. The most important changes include adding visually hidden headings for screen readers, updating the `CheckboxFilter` component to include group names, and improving the `ResultsCount` component to display the search query.
Accessibility improvements:
* [`app/search/templates/django-fbr.html`](diffhunk://#diff-5679603b023b699e9a2abab1b04ff5b1adac6854be9617a20812b14cc595155bR224): Added a visually hidden heading for search results to improve accessibility.
* [`react_front_end/src/App.js`](diffhunk://#diff-cbb35501ca550115b2dcf8e93872e0a02dbd8b9f5c7ff6e0df59de01ee017d7bR254): Added visually hidden headings for search results to improve …

ORPD-251 - Accessibility

---

app/search/views.py
fbr/urls.py

This pull request includes several changes aimed at improving the error handling and data consistency in the CSV download functionality. The most important changes involve updating the data fields in the CSV output and improving the error response mechanism.
* [`app/search/views.py`](diffhunk://#diff-526c4d0f8b7d6ddbd03c4c195062e16fefdc69d97783853d94b55e659ed399eaL169-R174): Updated the `date_published` and `last_updated` fields to use `source_date_issued` and `source_date_modified` for better data consistency. Added `external_url` to the CSV output.
* [`app/search/views.py`](diffhunk://#diff-526c4d0f8b7d6ddbd03c4c195062e16fefdc69d97783853d94b55e659ed399eaL185-R193): Changed the error response in `download_csv` to render a custom "page not found" HTML template with a 404 status instead of …

Adds external_url and fixes dates on CSV download

---

.run/Local _ Server.run.xml
app/search/utils/calculate_score.py
app/search/utils/search.py
manage.py
test_server_conf/README
test_server_conf/local_test_conf.env

- Added `clean_up_tokens` function for token parsing with optional quoting.
- Improved `calculate_score` function using `SearchVector` and `SearchRank` to enhance field prioritization and relevance scoring.
- Updated `manage.py` to enable local test server configuration via environment variables.
This update optimizes search functionality and eases local development setup.

feat(orpd-272): enhance token cleanup and scoring logic

---

app/search/views.py

Refactor the search result type labeling to utilize document type groups. This enhances labeling consistency and maintainability by centralizing the matching logic in a utility function.

refactor: update search result type labeling logic

---

app/cache/public_gateway.py
fbr/urls.py

```
This pull request introduces two key changes:
1. **JSON Correction Utility**:
- Added `rectify_malformed_json_to_list` to handle and fix malformed JSON-like strings.
- Updated `related_legislation` logic in `PublicGateway` to use this utility for valid JSON parsing.
- Commented out unused cache endpoint registration in `urls.py` for better clarity.
2. **Consistent Search Result Labeling**:
- Refactored type labeling logic for search results by integrating document type groups.
- Ensured centralized and maintainable labeling for search result types.
```

feat:add utility for JSON correction and improve result labeling logic

---

app/search/utils/documents.py
app/search/views.py

This pull request introduces validation for related legislation JSON data by adding a `validate_related_legislation` function. It ensures the data has the correct structure and includes required fields. Additionally, updates were made to the `views` logic to handle validation errors and improve error logging for better data reliability and error tracking.

chore:add validation for related legislation JSON

---

front_end/stylesheets/filters.scss
front_end/stylesheets/helpers.scss
react_front_end/src/components/PublisherFilters.js

This pull request refactors and enhances the styling and functionality of filters in both the front-end stylesheets and React components. The most notable changes include moving reusable scrollbar styles to `filters.scss`, adding a new `highlighted` class for checkbox filters, and improving the state management of highlighted options in the `PublisherFilters` React component.
* Moved reusable scrollbar styles, including custom scrollbar appearance and behavior, from `helpers.scss` to `filters.scss` for better organization and maintainability. [[1]](diffhunk://#diff-ab7625a5e6d1666ecb6e2cdacfa3dcdbb05937c1e2637efba95d031316770f55R53-R109) [[2]](diffhunk://#diff-29ea7f661404edd05410dfd597dfac25da31653f3cfccb909b202b62f2d81c95L5-L65)
* Added a new `.highlighted` class for checkbox filters to …

ORPD-308 Accessibility fixes
